### ISSUE TITLE
请问这个是框架自带的bug

### ISSUE THREAD

**Issue by 1144075799** [laincarl/react-gantt-component#4]
<img width="1116" alt="WeChatda2b4dd9d274f6ec9df6f6bdc6e88ca5" src="https://user-images.githubusercontent.com/38463468/115200884-48140480-a127-11eb-9d9c-7f0f5c96e4fa.png">

**Comment by laincarl** [comment]
@1144075799 mobx相关的依赖放在了开发依赖中，如果使用需要自行安装，版本参考组件内的版本https://github.com/laincarl/react-gantt-component/blob/master/package.json
